version: '3'

volumes:
  mongodb_data:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
    - API_HOST= "${HOSTNAME}"_app
    - API_PORT= 8081
    - MONGODB_HOST= "${HOSTNAME}"_db
    - MONGODB_PORT= 27017
    depends_on:
      - db
    
  db:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data