version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
    - API_HOST=startgolang-ap-1
    - API_PORT=8081
    - MONGODB_HOST=startgolang-db-1
    - MONGODB_PORT=27017
    depends_on:
      - db
    volumes:
      - var/jenkins_home/mongodb:/data/db  # 挂载本地目录用于持久化 MongoDB 数据
    
  db:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - var/jenkins_home/mongodb:/data/db  # 挂载本地目录用于持久化 MongoDB 数据